CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target TEXT NOT NULL,
  status TEXT NOT NULL,
  statusCode INTEGER,
  responseTimeMs INTEGER,
  error TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
