name = "estat-healthcheck-backend"
main = "src/index.ts"
compatibility_date = "2024-05-20"

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "estat_health_history"
database_id = "2867db9a-c3b5-4995-b127-36434b8a5ad1"
